### ISSUE TITLE
[Feature Request] show energy & power usage

### ISSUE THREAD

**Issue by jonathanhofman81** [crownstone/crownstone-home-assistant#2]
Would it be difficult to add support for energy usage and power usage? It is a nice feature and would make nice dashboards in HA. I wouldn't need a real time 'high performance' energy usage. Updates of the energy usage in 15 mins or 1 hour could be sufficient (1 minute intervals would be better). Power usage could be less frequent snapshots also.

BTW I'm using the USB stick

**Comment by RicArch97** [comment]
Thanks for your feature request!

Power usage sensor is on the roadmap for the next update! However, I currently don't have time to work on that so I can't give you an exact time/date for when this will be implemented into the integration

**Comment by mrquincle** [comment]
Hi! 

The support for energy and power monitoring is already implemented in the firmware and is communicated through the mesh towards the dongle. The python UART library is also able to receive this. The rate is at around 1 message per minute.

This feature request would then require integration of this function within Home Assistant. We'll discuss internally when it's likely that this function will be there. Now, I'd estimate it would arrive on our planning in around 4,5 sprints (couple of months). In the meantime, feel free to do a pull request. :-)

**Comment by jonathanhofman81** [comment]
Hi,

Tnx, the confirmation that it is already part of the mesh communication and
the uart library for the dongle motivates indeed to start implementing it
myself if time permits. If so, I will certainly create a pull request. Good
to know that it is on the roadmap somewhere and will be coming if I'm not
able to add it sooner.

BTW: the integration with Home Assistant is quite nice. The setup of new
devices works quite well out of the box with very little steps. So well
done :-). Of course, there are things to add and improve, but I'm very
pleased already.


Op di 27 okt. 2020 om 10:45 schreef Anne van Rossum <
notifications@github.com>:

**Comment by RicArch97** [comment]
Hey! Thanks for your reply!

I'm the developer of the entire integration so far and I'm glad you like it! 

The power usage implementation is something I could add in a day or two, since all of the code is known to me (including all of the code of Home Assistant core). I might look at it this weekend and add support for energy usage updates using the USB dongle. We can look into adding support for periodic polling (~10 minutes interval) of the energy usage for non-usbdongle users later on.

Oh btw, what are the things you think could be improved in the integration? Thanks!

**Comment by RicArch97** [comment]
Quick update on the progress:

Next update will be quite large and will include more than just the power usage. dependencies have been updated with new features & bug fixes, and the integration will support updating during runtime, any changes made in the app (updating name, adding/ deleting Crownstones etc) will immediately be processed in HA.

The cloud switch command has been reworked so that every command comes in, even when switching really fast or switching multiple Crownstones, so state updates coming from the app will now also be instantly processed in HA, for both cloud and usb.

As for the power usage measurements, this will only be possible using the Crownstone USB. We are looking at making it as accurate as possible. Without the USB the entities state will be "unavailable".

I'm planning on including the updated uart lib with the new protocol with this update. So release will be done after that releases.

**Comment by jonathanhofman81** [comment]
Looks great! Also the update of states will be very welcome. Would that mean that also changed state due to switchcraft will be reflected in HA?

Looking forward to the release and will be happy to try it out.

**Comment by hillstub** [comment]
Another very happy user. Good to hear you guys are working on this and looking forward to implement tracking of power usage in my home assistant set-up as well!

**Comment by ddcbe** [comment]
Same here! Since this integration the crownstones really show their potential!

**Comment by RicArch97** [comment]
> Looks great! Also the update of states will be very welcome. Would that mean that also changed state due to switchcraft will be reflected in HA?
> 
> Looking forward to the release and will be happy to try it out.

The state change due to Switchcraft will be reflected in HA, but only using the Crownstone USB dongle. When state changes are coming from the app, they are reflected in HA by both Cloud and USB in the new version.

**Comment by ddcbe** [comment]
Hi, thanks for the new release! I tried it and it works but not for all crownstones:
In my setup I have 5 crownstones ( 4 zeros one cronwstone one). For two of them, the power usage is shown. For the other 3, there is no entity reflecting the power consumption. I already tried by deleting the integration and adding it again but that doesn't make any difference. Any suggestions or additional info which I can provide?

**Comment by AlexDM0** [comment]
Hi, just small question before we continue, are all Crownstones updated to the latest firmware?

EDIT: removed email history

**Comment by RicArch97** [comment]
> Hi, thanks for the new release! I tried it and it works but not for all crownstones:
> In my setup I have 5 crownstones ( 4 zeros one cronwstone one). For two of them, the power usage is shown. For the other 3, there is no entity reflecting the power consumption. I already tried by deleting the integration and adding it again but that doesn't make any difference. Any suggestions or additional info which I can provide?

Thanks for your feedback!

Do you have any logs with error messages by any chance? You can find them in Configuration -> Logs.

**Comment by ddcbe** [comment]
Hi,

all cronwstones are running the latest firmware: 5.2.1

This are the entries I could find in the logs:
2020-11-21 21:03:51 ERROR (MainThread) [homeassistant.components.sensor] Platform crownstone does not generate unique IDs. ID 2 already exists - ignoring sensor.living_2
2020-11-21 21:03:51 ERROR (MainThread) [homeassistant.components.sensor] Platform crownstone does not generate unique IDs. ID 3 already exists - ignoring sensor.master_bedroom
2020-11-21 21:03:51 ERROR (MainThread) [homeassistant.components.sensor] Platform crownstone does not generate unique IDs. ID 4 already exists - ignoring sensor.overloop

**Comment by RicArch97** [comment]
Hi

In case of entity ID's, home assistant is initially in charge of creating them and providing an entity ID that does not exist yet. It does that by combining the platform and the entity's name. So in case of the power usage entities, they should be called:

* Overloop Power Usage, with entity ID `sensor.overloop_power_usage`
* Master Bedroom Power Usage, with entity ID `sensor.master_bedroom_power_usage`

for example.

I can advise you to:
- Remove the Crownstone integration from Configuration -> integrations
- Restart Home Assistant from Server controls -> restart
- Setting it up again in Configuration -> integrations -> Crownstone

I will be further investigating this to see if i can ensure unique id generation. 

Thanks for your reply!

**Comment by ddcbe** [comment]
Hi,

thanks for the reply. I did as you suggested but the result is still the same. I also tried to rename the crownstone in the app so the get another name but it didn't help so far. Let me know if you need any further information, ....

Thanks!

**Comment by RicArch97** [comment]
I believe i have found the issue, update will come asap!

**Comment by ddcbe** [comment]
That's fast! Awesome! Thanks for looking into this. The crownstones are now showing their full potential for me!

**Comment by RicArch97** [comment]
Issue should be fixed in [release 1.5.1](https://github.com/crownstone/crownstone-home-assistant/releases/tag/v1.5.1)

It is recommended to remove the integration and re-add it again after updating,  because of the new ID's that will be generated (to avoid duplicates).

Let us know if it works correctly now!

**Comment by hillstub** [comment]
For me that did the job. However, after removing the integration and installing it again, I got a lot of *_2 entities (e.g. light.bedlamp_2). To get rid of that, I had to remove the crownstone entries from .storage/core.device_registry and .storage/core.entity_registry.

**Comment by RicArch97** [comment]
> For me that did the job. However, after removing the integration and installing it again, I got a lot of *_2 entities (e.g. light.bedlamp_2). To get rid of that, I had to remove the crownstone entries from .storage/core.device_registry and .storage/core.entity_registry.

Hmm that basically means the "old" entity id's still exist in home assistant after unloading an integration. Not sure if Home Assistant removes these by itself after a while, or that a restart is required.

I guess the best way to start clean is by removing the integration, restarting HA and then adding the integration again

**Comment by hillstub** [comment]
I thought I did restart Home Assistant after removing the integration, so you might be right in that it doesn't clean up properly..

**Comment by jonathanhofman81** [comment]
I indeed removed the integration before updating and added it again after updating. That seems to work as expected (I didn't had duplicates). Furthermore, now all devices have a power usage entity. So that seems to work nice. That was a nice quick fix. Tnx!

**Comment by ddcbe** [comment]
Thanks! It works perfect! Great job!

**Comment by RicArch97** [comment]
Added support for energy usage measurements in version 1.6.0.
