### ISSUE TITLE
Crownstone Home Assistant Integration - Official

### ISSUE THREAD

**Issue by mrquincle** [crownstone/crownstone-home-assistant#3]
Check if there are things to be done for the pull request towards the official channel. It might be ready. That would be nice!

Pull request: https://github.com/home-assistant/core/pull/37005

**Comment by mrquincle** [comment]
The current pull request is https://github.com/home-assistant/core/pull/50677 which has lots and lots of changes and updates. Thanks  to the Home Assistant maintainers / contributors for their remarks. 

For everyone wondering if they can use this plugin in Home Assistant, yes you can, but for the time being it's through HACS. Follow these steps:

- https://crownstone.rocks/integrations/home-assistant/

If there are code suggestions that might accelerate adoption feel free to do a PR. Otherwise, subscribe to this issue and see when it's closed to know when the Crownstone Home Assistant integration is official!

**Comment by RicArch97** [comment]
All the PR's for the official first version of the Crownstone integration in Home Assistant have been merged.

The integration will be included starting from HA version 2021.10, which will officially release on October 6th.
