### ISSUE TITLE
Energy is 0kWh using dongle

### ISSUE THREAD

**Issue by bvmensvoort** [crownstone/crownstone-home-assistant#8]
I'm using the Crownstone beta version on Home Assistant Docker with the USB Dongle. Switching works, but energy readings don't.

Installing seems fine, when logging in and selecting the USB Dongle, I see my Crownstones in the Overview.
Each item has:
Connection: USB Dongle
Power: 0 W
Energy: 0 kWh
Light: <switch on/off>
![Crownstone HA](https://user-images.githubusercontent.com/2351505/188328233-acf38129-c257-45ec-9f5f-3befda39f73f.PNG)

Switching the light works.
Clicking on either Power or Energy shows a graph with only 0 as a value.
In the Crownstone App I see energy readings; the USB Dongle is in the same sphere (and green in the app).
I'd try to set a different USB Dongle device (/dev/USBttyx), but then I get an error message in the logbook. So a bad USB Dongle setup is unlikely to be the cause.

The Logbook mentions for each Connection:
- <Device> Connection became unavailable
- <Device> Connection changed to Cloud
- <Device> Connection became unavailable
- <Device> Connection changed to USB Dongle
- <Device> Connection became unavailable 

The Docker is run in privileged and unprivileged mode, but the outcome is the same.
Homeassistant version used is 2022.8.2. Crownstone Plugin version is 2.0.6.

I would like to see the energy readings. How to proceed?

**Comment by RicArch97** [comment]
Hi,

My guess is that the Crownstone UART manager failed to establish a connection to the device. You can see logs regarding `crownstone_uart` in Settings -> System -> Logs. You may have to enable the logger in `configuration.yaml` for this library to info or debug to see more logs;
```yaml
logger:
    default: info
    logs:
        crownstone_uart: debug
```
One of the reasons the connection may have failed is that the USB device wasn't exposed to docker, see https://www.home-assistant.io/installation/linux#exposing-devices
Also make sure the user running the container has privileges to access serial ports, by being in the correct group. See https://github.com/crownstone/crownstone-lib-python-uart#requirements-for-the-crownstone-usb for instructions on that.

The integration is designed to fall back to use the cloud when an usb connection is not available (or not functional) hence you could still switch Crownstones :-)

**Comment by bvmensvoort** [comment]
Thanks for the information! I tried the suggested configuration, but unfortunately I don't see any hint of where it might go wrong.

- The USB device is exposed to the Docker container. This setup works with another USB device, and I get an error when I purposely make this config invalid.
- I wasn't manage to verify the user and group (don't know how), but I can do this if it is still necessary to lookup. If it helps, another USB device I can use from this container.
- I was able to get some detailed logs with the suggested setup.
Below are all the log entries mentioning crownstone (no errors are shown in the entire log):
`INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'group', 'blueprint', 'device_automation', 'timer', 'persistent_notification', 'input_select', 'script', 'tts', 'sun', 'trace', 'media_source', 'scene', 'repairs', 'mqtt', 'search', 'config', 'homeassistant_alerts', 'mobile_app', 'counter', 'input_boolean', 'system_health', 'zone', 'onboarding', 'hacs', 'automation', 'person', 'crownstone', 'my', 'logbook', 'prometheus', 'analytics', 'auth', 'input_number', 'energy', 'input_datetime', 'map', 'tag', 'image', 'application_credentials', 'diagnostics', 'history', 'input_text', 'lovelace', 'input_button', 'default_config'}`
`INFO (MainThread) [homeassistant.setup] Setting up crownstone`
`INFO (MainThread) [homeassistant.setup] Setup of domain crownstone took 0.0 seconds`
`DEBUG (Thread-3) [crownstone_uart.core.uart.UartManager] Initializing... /dev/ttyUSB1 230400`
`DEBUG (Thread-3) [crownstone_uart.core.uart.UartManager] Setup connection to /dev/ttyUSB1`
`DEBUG (Thread-3) [crownstone_uart.core.uart.UartManager] Setting up connection... port=/dev/ttyUSB1 baudRate=230400 performHandshake=False`
`DEBUG (Thread-4) [crownstone_uart.core.uart.UartBridge] UartBridge: Initializing serial on port /dev/ttyUSB1 with baudrate 230400`
`DEBUG (Thread-4) [crownstone_uart.core.uart.UartBridge] Read starting on serial port./dev/ttyUSB1 True`
`INFO (Thread-3) [crownstone_uart.core.uart.UartManager] Connection established to /dev/ttyUSB1`
`INFO (MainThread) [homeassistant.components.light] Setting up light.crownstone`
`INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.crownstone`

It looks like a correct log to me (Read starting.. True), although I don't know what a good log looks like.

**Comment by RicArch97** [comment]
Hi,

Those logs do seem like it's connected properly.

I've set up a docker myself to maybe reproduce this, but everything worked as expected on my end, using:
```
docker run -d \
  --name homeassistant \
  --privileged \
  --restart=unless-stopped \
  -e TZ=Europe/Amsterdam \
  -v /home/ricardo/Documents/ha-docker:/config \
  --network=host \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  ghcr.io/home-assistant/home-assistant:stable
```
Where `/dev/ttyUSB0` is of course the Crownstone dongle.
![2022-09-06T22:31:23,737744302+02:00](https://user-images.githubusercontent.com/61013287/188732771-b075f512-37e4-4292-9e62-49884b918434.png)

Then after installing HACS and the Crownstone Beta integration, i was able to receive my power and energy usage updates instantly.

> I wasn't manage to verify the user and group (don't know how), but I can do this if it is still necessary to lookup. If it helps, another USB device I can use from this container.

You can check the groups for your user using the `groups` command. For example my user is `ricardo`, so would run
`groups ricardo` which returns the current groups my user is in. (in my case, quite a lot)
```console
$ groups ricardo
ricardo : ricardo wheel dialout audio video storage network kvm input xbuilder socklog bluetooth libvirt docker gamemode nixbld
```
The important one here is the `dialout` group. For Arch Linux and it's derivatives that would be `uucp`. If your user is not in this group yet, you can add your user by:
```console
$ sudo usermod -a -G dialout your_username
```
where you replace `your_username` with the name of your user.

I'll have to further investigate this issue to know what could have happened.

**Comment by AlexDM0** [comment]
Hi, just to check, did you add the dongle to your sphere using the Crownstone consumer app?

**Comment by bvmensvoort** [comment]
Thanks for the detailed reply. Unfortunately no readings yet.
I used the docker command suggested and noticed a few differences:
- This setup uses the host network; my initial setup used bridge instead
- My dongle has a different name (maybe the firmware is outdated, since I have an early dongle)
- It seems to scan all my USB devices and overrule the device mapping

![image](https://user-images.githubusercontent.com/2351505/188963364-20adea8f-374a-4b3f-bde8-edf83d90e500.png)
(I used the ttyUSB1 here)

The log shows the same entries, with the last two lines replaced with:
`INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.crownstone`
`INFO (MainThread) [crownstone_sse.async_client] Crownstone SSE client is running.`
`INFO (MainThread) [homeassistant.components.light] Setting up light.crownstone`

About the groups. On the host it is set up as you decribed (the default setup on Raspberry Pi):
`$ groups pi`
`pi : pi adm dialout cdrom ...`
And `pi` is the only user on the host system.

Finally, I did add the dongle in the sphere using the Crownstone consumer app.

**Comment by RicArch97** [comment]
Just to be sure, what was the full command you ran for your docker? It had to be different from mine at least since you have multiple devices

**Comment by bvmensvoort** [comment]
Luckily I had another Raspberry Pi and could try a clean installation. It works! A summary what does work on that installation:
- Docker container using bridge network
- Docker container not privileged
- Docker container with multiple USB serial devices (1 shared though)
- USB device with alias using udev rule
- Different USB ports (2.0 or 3.0)

Then I tried using [crownstone-uart](https://github.com/crownstone/crownstone-lib-python-uart) Python directly on the hosts. Using the [uartEcho.py example](https://github.com/crownstone/crownstone-lib-python-uart/blob/master/examples/uartEcho.py).
Thee hosts are physically next to each other. After running the command I get different results:
- The host that doesn't work: _Received multiple start tokens_
- The host that does work: _Received payload {...}_, and one time a saw a few _Received multiple start tokens_.

This log entry (_Received multiple start tokens_) is used in [UartReadBuffer.py:56](https://github.com/crownstone/crownstone-lib-python-uart/blob/master/crownstone_uart/core/uart/UartReadBuffer.py). But I am not sure what it means or which device has incorrect _start tokens_.

About the run command:
`sudo docker run -d   --name homeassistant-crownstonetest    --restart=unless-stopped   -e TZ=Europe/Amsterdam   -v HomeAssistant-crownstonetest:/config  -p 8124:8123   --device /dev/ttyUSB-crownstonehub:/dev/ttyUSB-crownstonehub   ghcr.io/home-assistant/home-assistant:stable`
And I have a udev rule (in `/etc/udev/rules.d/99-usb-serial.rules`) on both hosts:
`SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="016788DB", SYMLINK+="ttyUSB-crownstonehub"`. 
It results in this listing of `/dev` (amond others).
```
root dialout 188,   0 ttyUSB0
root root           7  ttyUSB-crownstonehub -> ttyUSB0

```

**Comment by bvmensvoort** [comment]
Update: Good news! The problem is solved.
Apparently the Crownstones were too far away for the dongle to reach. I put an extra Crownstone in between and I get readings in HomeAssistant and payload information when running the python example. I don't know why the device from the previous post reacted differently at first.

However, two messages in the log entries remain:
`WARNING (Thread-3) [crownstone_uart.core.uart.UartReadBuffer] MULTIPLE START TOKENS`
`DEBUG (Thread-3) [crownstone_uart.core.uart.UartReadBuffer] Multiple start tokens: sizeToRead=256 bufLen=15 buffer=[0, 0, 127, 39, `...`]`
and:
`DEBUG (Thread-3) [crownstone_uart.core.uart.UartParser] Unknown opCode: 10111`

I don't know what they mean. Is it okay to have these?

**Comment by mrquincle** [comment]
@RicArch97, @AlexDM0  There's a remaining question here. What's the answer? :-)

**Comment by vliedel** [comment]
> Update: Good news! The problem is solved. Apparently the Crownstones were too far away for the dongle to reach. I put an extra Crownstone in between and I get readings in HomeAssistant and payload information when running the python example. I don't know why the device from the previous post reacted differently at first.
> 
> However, two messages in the log entries remain: `WARNING (Thread-3) [crownstone_uart.core.uart.UartReadBuffer] MULTIPLE START TOKENS` `DEBUG (Thread-3) [crownstone_uart.core.uart.UartReadBuffer] Multiple start tokens: sizeToRead=256 bufLen=15 buffer=[0, 0, 127, 39, `...`]` and: `DEBUG (Thread-3) [crownstone_uart.core.uart.UartParser] Unknown opCode: 10111`
> 
> I don't know what they mean. Is it okay to have these?

Good to hear :)

Regarding the "multiple tokens" log, that's usually due to noise on the line, you can ignore it. The unknown opcode is because the crownstone firmware is newer than the library that parses the data, this doesn't hurt either :)
